
export const CONTACT_MESSAGE_REQUEST='CONTACT_MESSAGE_REQUEST'

export const CONTACT_MESSAGE_SUCCESS='CONTACT_MESSAGE_SUCCESS'

export const CONTACT_MESSAGE_FAIL='CONTACT_MESSAGE_FAIL'



export const ADD_MESSAGE_REQUEST='ADD_MESSAGE_REQUEST'

export const ADD_MESSAGE_SUCCESS='ADD_MESSAGE_SUCCESS'

export const ADD_MESSAGE_FAIL='ADD_MESSAGE_FAIL'