export const USERS_LIST_REQUEST='USERS_LIST_REQUEST'

export const USERS_LIST_SUCCESS='USERS_LIST_SUCCESS'

export const USERS_LIST_FAIL='USERS_LIST_FAIL'



export const CONTACTS_LIST_REQUEST='CONTACTS_LIST_REQUEST'

export const CONTACTS_LIST_SUCCESS='CONTACTS_LIST_SUCCESS'

export const CONTACTS_LIST_FAIL='CONTACTS_LIST_FAIL'



export const LOGIN_REQUEST='LOGIN_REQUEST'

export const LOGIN_SUCCESS='LOGIN_SUCCESS'

export const LOGIN_FAIL='LOGIN_FAIL'

export const LOGOUT_SUCCESS='LOGOUT_SUCCESS'





export const REGISTER_REQUEST='REGISTER_REQUEST'

export const REGISTER_SUCCESS='REGISTER_SUCCESS'

export const REGISTER_FAIL='REGISTER_FAIL'